name: Clan
main: de.treona.clan.Clans
version: 1.0.0
author: Treona
description: Create and manage your clans with Clan.

commands:
  clan:
    description: Clans Clan command.
    usage: /cl
    aliases: [cl]