name: Clans
main: de.treona.clans.Clans
version: 1.1.4
author: Treona
description: Create and manage your clans with this Clans-Api.

commands:
  clan:
    description: Clans Clan command.
    usage: /cl
    aliases: [cl, clans]